### ISSUE TITLE
Can't start up

### ISSUE THREAD

**Issue by littleantfly** [artemMartynenko/spring-cloud-gateway-oauth2-sso-sample-application#1]
Hello, I downloaded your example, but the example needs to have a certificate authority to start, can you disclose the code of the certificate center? Thank you!
I tried to write it myself, but I couldn't start it.

**Comment by artemMartynenko** [comment]
Hello. Those example is also about JWT, which need to have a CA for token validation. You can use standard spring security params like jwk-set-uri and use github (or something else) as token provider like in this [example](https://github.com/spring-projects/spring-security/tree/5.1.1.RELEASE/samples/boot/oauth2login-webflux).   and use PreOAuth2SsoRoutingFilter for tokens proxy. Just  exclude ReactiveJwtDecoder bean injection from JwtConfiguration.class and let Spring Boot and Spring Security do it instead of you.
